import "~/styles/globals.css"
import "~/styles/colors.css"

import { Inter } from "next/font/google"

import { jaro_font, jetbrains_font } from "~/lib/fonts"
import { AppProviders } from "./_providers"

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-sans",
})

export const metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className="max-h-screen bg-background">
			<body
				className={`font-sans ${inter.variable} ${jetbrains_font.variable} ${jaro_font.variable} dark h-screen w-full overflow-auto`}>
				<AppProviders>{children}</AppProviders>
			</body>
		</html>
	)
}
